#!/usr/bin/env bash
# duplicate the web-01 to be web-02

# updating the system and installing nginx
function install() {
	command -v "$1" &> /dev/null

	# disabling shellcheck SC2181
	if [ $? -ne 0 ]
	then
		sudo apt-get update -y
		sudo apt-get install -y "$1"
		echo -e "\n"
	else
		echo -e "${1} is already installed\n"
	fi
}

#installing nginx now
install nginx

# firewall: allow nginx
sudo ufw allow 'Nginx HTTP'

# changing user ownership
if [ -d "/var/www" ]
then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi

# creating an index file
echo "Hello World!" > /var/www/html/index.html

# create page not found file
echo "Ceci n'est pas une page" > /var/www/html/not_found_404.html

# backup
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.bckp

# server configuration
configuring_server=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://youtube.com permanent;
		}
		error_page 404 /not_found_404.html;
		location = /not_found_404.html {
			internal;
		}
}"

# ignoring SC2154 for shellcheck
echo "$configuring_server" | sudo tee /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
	sudo service nginx start
else
	sudo service nginx restart
fi
